auction/urls.py
from django.urls import path

from .views import (
    auction_gallery,
    item_details,
    create_auction,
    my_auctions,
    place_bid,
    update_bid
)


from .views import dashboard


app_name = 'auction'

urlpatterns = [
    path('auction-gallery/', auction_gallery, name='auction-gallery'),
    path('item/<str:slug>/', item_details, name='item-detail'),
    path('create-auction/', create_auction, name='create-auction'),
    path('my-auctions/', my_auctions, name='my-auctions'),
    path('item/<str:slug>/place-bid/', place_bid, name='place-bid'),
    path('item/<str:slug>/<str:hashed_id>/update-bid/',
        update_bid,
        name='update-bid'
    ),
    
    path('', dashboard, name='dashboard'),

    
]

authentication/urls.py
from django.urls import path
from .views import user_login, logout

from django.urls import path

app_name = 'authentication'

urlpatterns = [
    path('admin/', user_login, name='admin-login'),
    path('login/', user_login, name='user-login'),
    path('logout/', logout, name='logout'),
]

taka_school/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('system-admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('auction.urls', namespace='auction')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

templates/partials/_alert.html
{% load static %}

{% block alert %}

    <div class="col-lg-12 col-md-12 col-sm-12 text-center"
         id="alert-msg">
        <!-- Alert -->
        <div class="d-flex justify-content-center align-content-center">
            {% if messages %}
                {% for message in messages %}
                    <div class="alert alert-{{ message.tags }} alert-dismissible text-center"
                         role="alert">
                    <button type="button" class="close" data-dismiss="alert"
                            aria-label="Close"><span
                            area-hidden="ture">&times;</span></button>
                    <strong>
                        {% if message.level == DEFAULT_MESSAGE_LEVELS.SUCCESS %}
                            <span class="txt1" style="color:green;">
                <i class="fa fa-check-circle" aria-hidden="true"></i>
              </span>SUCCESS{% else %}
                            <span class="txt1" style="color:#ff462e;">
                <i class="fa fa-exclamation-circle"></i>
              </span>{{ message.tags|upper }}{% endif %}!
                    </strong>{{ message }}
                {% endfor %}
            </div>
            {% endif %}
        </div>
        <!--  END Alert -->
    </div>



    <script>
        // alert message fadeout
        setTimeout(function () {
            $('#alert-msg').fadeOut('slow');
        }, 5500);
    </script>
{% endblock %}

templates/partials/_css.html
{% load static %}
<!-- Font Awesome -->
<link rel="stylesheet"
      href="https://use.fontawesome.com/releases/v5.11.2/css/all.css">
<!-- Bootstrap core CSS -->
<link rel="stylesheet"
      href="{% static 'css/bootstrap.min.css' %}">
<!-- Material Design Bootstrap -->
<link rel="stylesheet"
      href="{% static 'css/mdb.css' %}">
<!-- Animations -->
<link rel="stylesheet"
      href="{% static 'css/modules_/animations-extended.min.css' %}">
<!--  custom styles -->
<link rel="stylesheet" href="{% static 'css/style.css' %}">

templates/partials/_navbar.html
{% load static %}
<!-- Navbar -->
<nav class="bg-blue navbar fixed-top navbar-expand-lg scrolling-navbar double-nav mt-2">

    <!-- Logo -->
    <div class="logo-sn waves-effect mr-auto ml-3">
        <div class="text-center">
            <a href="/" class="pl-0"
               style="font-style: ;font-size: 1.4rem;">
                Ebay Auction
            </a>
        </div>
    </div>

    <div class="d-flex">
        <!-- Navbar links -->
        <ul class="nav navbar-nav nav-flex-icons ml-auto"
            style="font-size: 14px;">
            <li class="nav-item ">
                <a href="{% url 'auction:dashboard' %}" class="nav-link waves-effect
{% if active == 'dashboard' %} 
                      nav-item-selected text-black font-weight-bold {% endif %}">

                    <span class="clearfix d-none d-sm-inline-block">
                        Dashboard
                    </span></a>
            </li>
            {% if request.user.is_admin %}
                <li class="nav-item ">
                    <a href="{% url 'auction:auction-gallery' %}"
                       class="nav-link waves-effect font-weight-bold
                    {% if active == 'auction_gallery' %} 
                      nav-item-selected text-black {% endif %}">
                        <span class="clearfix d-none
                            d-sm-inline-block">Auction Gallery</span></a>
                </li>
            {% endif %}

            {% if not request.user.is_admin %}
            <li class="nav-item">
                <a href="{% url 'auction:my-auctions' %}"
                   class="nav-link waves-effect
              {% if active == 'my_auctions' %} font-weight-bold
                      nav-item-selected text-black {% endif %}">
                    <span
                        class="clearfix d-none
                            d-sm-inline-block">My posted items</span></a>
            </li>
            {% endif %}
            <li class="nav-item dropdown">
                <a class="nav-link dropdown-toggle waves-effect" href="#"
                   id="userDropdown" data-toggle="dropdown"
                   aria-haspopup="true" aria-expanded="false">
                     <span
                        class="clearfix d-none d-sm-inline-block">
                    {{ request.user.username|upper }}</span>
                </a>
                <div class="dropdown-menu dropdown-menu-right"
                     aria-labelledby="userDropdown">
                    <a class="dropdown-item"
                       href="{% url 'authentication:logout' %}">Log Out</a>
{#                    <a class="dropdown-item"#}
{#                       href="{% url 'auction:create-auction' %}">Create#}
{#                        Auction</a>#}
                </div>
            </li>
        </ul>
        <!-- Navbar links -->
    </div>
</nav>
<!-- Navbar -->

templates/partials/_scripts.html
{% load static %}
<!-- JQuery -->
<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<!-- Bootstrap tooltips -->
<script type="text/javascript"
        src="{% static 'js/popper.min.js' %}"></script>
<!-- Bootstrap core JavaScript -->
<script type="text/javascript"
        src="{% static 'js/bootstrap.min.js' %}"></script>
<!-- MDB core JavaScript -->
<script type="text/javascript"
        src="{% static 'js/mdb.min.js' %}"></script>

<script>

    new WOW().init();

    // DatePicker Initialization
    $('.datepicker').pickadate({
        // Escape any “rule” characters with an exclamation mark (!).
        format: 'yyyy-mm-dd',
        formatSubmit: 'yyyy-mm-dd',
        hiddenPrefix: 'prefix__',
        hiddenSuffix: '__suffix',
        today: null
    })


    $('#auction_end_time').pickatime({
        // 12 or 24 hour
        twelvehour: false,
        // Light or Dark theme
       // darktheme: true
        close
    });

    // Tooltips Initialization
    $(function () {
        $('[data-toggle="tooltip"]').tooltip()
    })

    // Material Select Initialization
    $(document).ready(function () {
        $('.mdb-select').materialSelect();
    });

</script>


<!-- Charts -->
<script>

    // Total Auction Value chart
    let total_auction_value_ctx = document.getElementById("lineChart")
        .getContext('2d');
    let total_auction_value_chart = new Chart(total_auction_value_ctx, {
        type: 'line',
        data: {
            labels: [],
            datasets: [{
                label: "Total Auction Value",
                fillColor: "",
                backgroundColor: '',
                borderColor: '',
                data: [],
            }]
        },
        options: {
            legend: {
                labels: {
                    fontColor: "#fff",
                }
            }, scales: {
                xAxes: [{
                    gridLines: {
                        display: true,
                        color: "rgba(255,255,255,.25)"
                    },
                    ticks: {
                        fontColor: "#fff",
                    },
                }],
                yAxes: [{
                    display: true,
                    gridLines: {
                        display: true,
                        color: "rgba(255,255,255,.25)"
                    },
                    ticks: {
                        fontColor: "#fff",
                        beginAtZero: true
                    },
                }],
            }

        }
    });


    // Created completed auctions number CHART
    let number_of_auction_created_completed_ctx = document.getElementById("barChart")
        .getContext('2d');
    let number_of_auction_created_completed_Chart = new Chart(number_of_auction_created_completed_ctx, {
        type: 'bar',
        data: {
            labels: [],
            datasets: [
                {
                    label: '',
                    data: [],
                    backgroundColor: [],
                    borderColor: [],
                    borderWidth: 1
                },

                {
                    label: '',
                    data: [],
                    backgroundColor: [],
                    borderColor: [],
                    borderWidth: 1
                }
            ]
        },
        options: {
            scales: {
                yAxes: [{
                    ticks: {
                        beginAtZero: true
                    }
                }]
            }
        }
    });
</script>

<script>
    //================ Auction TOTAL VALUE ===============
    $(document).ready(function () {
        loadAllTotalValueCharts('day');  // default the day chart will be shown

        // if time range is change then show other chart
        $("#time_range_total_value").change(function () {
            const time_range_total_value = $("#time_range_total_value").val();
            loadAllTotalValueCharts(time_range_total_value);
        });
    });

    function loadTotalValueChart(chart, endpoint) {
        // Load the chart data with ajax call and set data to the chart
        $.ajax({
            url: endpoint,
            type: "GET",
            dataType: "json",
            success: (jsonResponse) => {
                // Extract data from the response
                {#const title = jsonResponse.title;#}
                const labels = jsonResponse.data.labels;
                const datasets = jsonResponse.data.datasets;
                // Reset the current chart
                chart.data.datasets = [];
                chart.data.labels = [];

                // Load new data into the chart
                chart.data.labels = labels;
                datasets.forEach(dataset => {
                    chart.data.datasets.push(dataset);
                });
                chart.update();
            },
            error: () => console.log("Failed to fetch chart data from " + endpoint + "!")
        });
    }

    function loadAllTotalValueCharts(time_range) {

        if (time_range === 'day' && window.location.pathname === '/') {
            {#console.log(' in day')#}
            loadTotalValueChart(total_auction_value_chart,
                `/chart/total-auction-value-per-day/`);
        } else if (time_range === 'hour' && window.location.pathname === '/') {
            loadTotalValueChart(total_auction_value_chart,
                `/chart/total-auction-value-per-hour/`);
        } else if (time_range === 'minute' && window.location.pathname === '/') {
            loadTotalValueChart(total_auction_value_chart,
                `/chart/total-auction-value-per-minute/`);
        }
    }
</script>

<script>
    $(document).ready(function () {
        loadAllCharts('day');  // default the day chart will be shown

        // if time range is change then show other chart
        $("#time_range").change(function () {
            const time_range = $("#time_range").val();
            loadAllCharts(time_range);
        });

    });

    function loadChart(chart, endpoint) {
        // Load the chart data with ajax call and set data to the chart
        $.ajax({
            url: endpoint,
            type: "GET",
            dataType: "json",
            success: (jsonResponse) => {
                // Extract data from the response
                {#const title = jsonResponse.title;#}
                const labels = jsonResponse.data.labels;
                const datasets = jsonResponse.data.datasets;

                // Reset the current chart
                chart.data.datasets = [];
                chart.data.labels = [];

                // Load new data into the chart
                chart.data.labels = labels;
                datasets.forEach(dataset => {
                    chart.data.datasets.push(dataset);
                });
                chart.update();
            },
            error: () => console.log("Failed to fetch chart data from " + endpoint + "!")
        });
    }

    function loadAllCharts(time_range) {
        if (time_range === 'day' && window.location.pathname === '/') {
            loadChart(number_of_auction_created_completed_Chart,
                `chart/created-completed-auctions-number-per-day/`);
        } else if (time_range === 'hour' && window.location.pathname === '/') {
            loadChart(number_of_auction_created_completed_Chart,
                `/chart/created-completed-auctions-number-per-hour/`);
        } else if (time_range === 'minute' && window.location.pathname === '/') {
            loadChart(number_of_auction_created_completed_Chart,
                `/chart/created-completed-auctions-number-per-minute/`);
        }

    }
</script>


<!-- Custom scripts -->
<script type="text/javascript"
        src="{% static 'js/scripts.js' %}"></script>