auction/urls.py
from django.urls import path

from .views import (
    auction_gallery,
    item_details,
    create_auction,
    my_auctions,
    place_bid,
    update_bid
)


from .views import dashboard


app_name = 'auction'

urlpatterns = [
    path('auction-gallery/', auction_gallery, name='auction-gallery'),
    path('item/<str:slug>/', item_details, name='item-detail'),
    path('create-auction/', create_auction, name='create-auction'),
    path('my-auctions/', my_auctions, name='my-auctions'),
    path('item/<str:slug>/place-bid/', place_bid, name='place-bid'),
    path('item/<str:slug>/<str:hashed_id>/update-bid/',
        update_bid,
        name='update-bid'
    ),
    
    path('', dashboard, name='dashboard'),

    
]

authentication/urls.py
from django.urls import path
from .views import user_login, logout

from django.urls import path

app_name = 'authentication'

urlpatterns = [
    path('admin/', user_login, name='admin-login'),
    path('login/', user_login, name='user-login'),
    path('logout/', logout, name='logout'),
]

taka_school/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    path('system-admin/', admin.site.urls),
    path('', include('authentication.urls', namespace='authentication')),
    path('', include('auction.urls', namespace='auction')),
]

if settings.DEBUG:
    urlpatterns += static(
        settings.MEDIA_URL,
        document_root=settings.MEDIA_ROOT
    )
    urlpatterns += static(
        settings.STATIC_URL,
        document_root=settings.STATIC_ROOT
    )

templates/admin_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ebay Auction</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'register/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'register/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">



</head>
<body>

    <!-- Sing in  Form -->
<section class="sign-in">
    <div class="container">
        <div class="signin-content">
            <div class="signin-image" id="m">
                <figure><img src="{% static 'register/images/signin-image.jpg' %}" alt="sing up image"></figure>
                <a href="{% url 'authentication:user-login' %}" class="signup-image-link">User Login</a>
            </div>

            <div class="signin-form">
                <h2 class="form-title">Log in</h2>
                <form action="{% url 'authentication:admin-login' %}" method="POST" class="register-form" id="login-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        <input type="text" name="username" id="username" placeholder="name" required/>
                    </div>

                    <div class="form-group">
                        <label for="password"><i class="zmdi zmdi-lock"></i></label>
                        <input type="password" name="password" id="password" placeholder="Password"/>
                    </div>


                    <div class="form-group form-button">
                        <input type="submit" name="admin-login" id="login" class="form-submit" value="Log in"/>
                    </div>
                    
                </form>
                
            </div>
        </div>
    </div>
</section>


    <!-- JS -->
    <script src="{% static 'register/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'register/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>

        
    </section>
</header>

<!-- SCRIPTS -->
<!-- Custom scripts -->

templates/auction_gallery.html
{% extends 'base.html' %}
{% block title %}Auction Gallery{% endblock %}
{% block main_content %}
    {% include 'item_gallery.html' %}
{% endblock %}

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport"
          content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta http-equiv="x-ua-compatible" content="ie=edge">
    <title>
        Ebay Auction | {% block title %}{% endblock %}
    </title>
    {% include 'partials/_css.html' %}
</head>

<body class="fixed-sn white-skin">

<!-- Main Navigation -->
<header>
    {% include 'partials/_navbar.html' %}
</header>

<!-- Main Navigation -->

<!-- Main layout -->
<main style="padding-top: 67px;">
    <div id="alert" class="wow fadeInDown position-absolute w-100"
         data-wow-delay="0.3s">
        {% block alert %}
            {% include 'partials/_alert.html' %}
        {% endblock %}
    </div>

    {% block main_content %}

    {% endblock %}
</main>
<!-- Main layout -->

<!-- Footer -->
<footer class="page-footer pt-0 mt-5 rgba-stylish-light">
    <!-- Copyright -->
    <div class="footer-copyright py-3 text-center">
        <div class="container-fluid">
            &copy; Copyright: <a
                href="#" target="_blank"> Md. Milon Sarker </a>
        </div>
    </div>

</footer>
<!-- Footer -->

<!-- SCRIPTS -->
{% include 'partials/_scripts.html' %}

</body>

</html>

templates/create_auction.html
{% extends 'base.html' %}
{% block title %}Create Auction{% endblock %}
{% block main_content %}

    <div class="row d-flex justify-content-center mt-4">
        <!-- column -->
        <div class="col-lg-7 mb-4">

            <!-- Card -->
            <div class="card card-cascade narrower">

                <div class="text-center m-2 mt-3">
                    <h4 class="mb-0 font-weight-bold dark-grey-text">
                        Create New Auction
                    </h4>
                </div>

                <div class="card-body card-body-cascade text-center">
                    <form id="auction_create_form" name="auction_create_form"
                          enctype="multipart/form-data"
                          method="POST"
                          action="{% url 'auction:create-auction' %}">
                        {% csrf_token %}
                        <!-- Name -->
                        <div class="md-form form-sm">
                            <input type="text" id="product_name"
                                   class="form-control validate"
                                   name="product_name"
                                   value="{{ product_name }}"
                                   required>
                            <label for="product_name"
                                   style="font-size:1rem;"
                                   class="">Product
                                Name</label>
                        </div>

                        <!-- Description -->
                        <div class="md-form mb-0">
                            <textarea type="text" id="product_description"
                                      class="md-textarea validate" cols="77"
                                      rows="1"
                                      name="product_description"
                                      required>{{ product_description }}</textarea>
                            <label for="product_description"
                                   style="font-size:1rem;">Product
                                Description</label>
                        </div>

                        <!-- Photo -->
                        <div class="md-form mt-0">
                            <div class="input-group">
                                <div class="input-group-prepend"
                                     style="margin-top: 12px;">
                                    <span class="input-group-text"
                                          id="inputGroupFileAddon01">
                                        Choose Product Photo</span>
                                </div>
                                <div class="custom-file">
                                    <input type="file"
                                           style="cursor:pointer;"
                                           name="product_photo"
                                           class="custom-file-input validate"
                                           id="product_photo" required
                                           aria-describedby="inputGroupFileAddon01">
                                    <label class="custom-file-label"
                                           for="product_photo"> </label>
                                </div>
                            </div>
                        </div>

                        <!-- min bid price -->
                        <div class="md-form ">
                            <input type="number" id="min_bid_price"
                                   name="min_bid_price"
                                   class="form-control"
                                   value="{{ min_bid_price }}"
                                   required>
                            <label for="min_bid_price"
                                   style="font-size:1rem;"
                                   class="form-label validate">
                                Minimum Bid Price (Dollar)</label>
                        </div>

                        <div class="row d-flex justify-content-around">
                            <!-- Auction end date -->
                            <div class="md-form w-50 pr-lg-5">
                                <input type="text"
                                       name="auction_end_date"
                                       id="auction_end_date"
                                       class="form-control datepicker"
                                       required>
                                <label for="auction_end_date">
                                    Select Auction End Date</label>
                            </div>

                            <!-- Auction end time -->
                            <div class="md-form w-50">
                                <input type="text"
                                       id="auction_end_time"
                                       name="auction_end_time"
                                       value="{{ auction_end_time }}"
                                       class="form-control timepicker"
                                       required>
                                <label for="auction_end_time"
                                       class="active">Select Auction End
                                    time</label>
                            </div>
                            <!--  Auction end time -->
                        </div>

                        <!-- Footer -->
                        <div class="modal-footer justify-content-center">
                           
                            <button type="submit" class="btn
                            btn-primary">Create Auction
                                <i class="fas fa-paper-plane ml-1"></i>
                            </button>
                        </div>
                    </form>

                </div>
            </div>
            <!-- Card -->
        </div>


    </div>

{% endblock %}

templates/dashboard.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Dashboard{% endblock %}

{% block main_content %}

    {% if not request.user.is_admin %}
        {% include 'item_gallery.html' %}
    {% endif %}

    {% if request.user.is_admin %}
{#        <!-- BUTTON: Create Auction Button -->#}
{#        <div class="container-fluid  ">#}
{#            <div class="ml-auto mb-0 mr-3 d-flex#}
{#            justify-content-end">#}
{#                <a href="{% url 'auction:create-auction' %}"#}
{#                   class="btn btn-outline-black btn-sm waves-button#}
{#                   waves-effect"#}
{#                   style="font-size: 15px;">#}
{#                    <i class="fas fa-plus-circle"></i> Create Auction#}
{#                </a>#}
{#            </div>#}
{#            <!-- BUTTON: Create Auction Button -->#}

            <!-- Section: Intro -->
            <section class="mt-md-4 pt-md-2 mb-5 pb-4">

                <!-- Grid row -->
                <div class="row d-flex justify-content-center">

                    <!-- Grid column -->
                    <div class="col-xl-5 col-md-6 mb-xl-0 mb-4" >

                        <!-- Card -->
                        <div class="card card-cascade cascading-admin-card d-flex justify-content-center align-items-center"
                             style="height: 333px;">

                            <!-- Card Data -->
                            <div class="admin-up" >
                          
                               
                            </div>

                            <!-- Card content -->
                            <div class="card-body card-body-cascade d-flex justify-content-center align-items-center">
                                <div class="data text-center mt-3 ">
                                    <p class="text-uppercase"
                                       style="font-size: 20px ">
                                        Running Auction</p>
                                    <h4 class="font-weight-bold dark-grey-text">
                                        {{ running_auctions_count }}</h4>
                                        <p class="card-text">Total number auction
                                            ({{ total_auctions }})
                                        </p>
                                </div>
                                
                            </div>

                        </div>
                        <!-- Card -->

                    </div>
                    <!-- Grid column -->

                    <!-- Grid column -->
                    <div class="col-xl-5 col-md-6 mb-xl-0 mb-4" id="a">

                        <!-- Card -->
                        <div class="card card-cascade cascading-admin-card"
                             style="height: 333px; weight:52px">

                            <!-- Card Data -->
                            <div class="admin-up">
                                
                                
                            </div>

                            <!-- Card content -->
                            <div class="card-body card-body-cascade d-flex justify-content-center align-items-center">
                                <div class="data text-center mt-2 ">
                                    <p class="text-uppercase"
                                       style="font-size: 20px">Running
                                        Auctions<br>
                                        Value</p>
                                    <h4 class="font-weight-bold dark-grey-text">
                                        ${{ running_auctions_total_value }}</h4>
                                </div>

                            </div>

                        </div>
                        <!-- Card -->

                    </div>
                    <!-- Grid column -->

                </div>
                <!-- Grid row -->

            </section>
            <!-- Section: Intro -->

    
        </div>
    {% endif %}
{% endblock %}

templates/item_gallery.html
{% load static %}
<div class="container">

    <!-- Section: product cards -->
    <section>
        <div class="row d-flex align-content-center">

            <h2 class="font-weight-bold  mt-lg-4"><strong>
                {% if '/my-auctions/' in request.path %}
                    My Auctions
                {% else %}
                    Auction Gallery
                {% endif %}
            </strong></h2>

            {% if not request.user.is_admin %}
                <!-- BUTTON: Create Auction Button -->
                <div class="ml-auto mb-0 mr-3 d-flex flex-column-reverse justify-content-center">
                    <a href="{% url 'auction:create-auction' %}"
                       class="btn btn-outline-black btn-sm waves-button
                waves-effect"
                       style="font-size: 15px;">

                        Create Auction
                    </a>
                </div>
                <!-- BUTTON: Create Auction Button -->
            {% endif %}

        </div>

        <div class="row pb-4">
            {% for product in products %}
                <div style="width: 50%">
                    <!-- Section: products -->
                    <section>
                        <!-- Card -->
                        <div class="card card-cascade narrower"
                             style="margin-top: 44px; height: 500px;">

                            <!-- Card image -->
                            <div class="view view-cascade overlay">
                                <img src="{{ product.photo.url }}"
                                     class="card-img-top"
                                     alt="{{ product.name }}" style="height:
                                      280px; border: 1px solid black;">
                                <a href="{% url 'auction:item-detail' product.slug %}">
                                    <div class="mask rgba-white-slight"></div>
                                </a>
                            </div>
                            <!-- Card image -->

                            <!-- Card content -->
                            <div class="card-body card-body-cascade">
                                <div class="d-flex justify-content-between">
                                    <div class="d-flex
                                    justify-content-sm-start w-50">
                                        <h5 style="color: #3a3d3d">
                                            <i class="fas fa-dollar-sign"></i>
                                            {% if product.get_max_bid is not None %}
                                                {{ product.get_max_bid.price }}
                                            {% else %}
                                                {{ product.min_bid_price }}
                                            {% endif %}
                                        </h5>
                                        
                                    </div>

                                    <h5 class="pink-text w-50 text-right">
                                        {% if product.get_is_auction_time_ended %}
                                            Auction Ended
                                        {% else %}
                                            {{ product.auction_end_date }}
                                        {% endif %}
                                    </h5>
                                </div>
                                <h6>
                                    {{ product.user.username|capfirst }}
                                </h6>
                                <!-- Title -->

                                <h4 class="card-title text-center">
                                    <a style="color:#0e6161"
                                       href="{% url 'auction:item-detail' product.slug %}"
                                       class="card-link waves-effect waves-ripple">
                                        {{ product.name }}
                                    </a>
                                </h4>

                                <!-- Text -->
                                <p class="card-text">
                                    {{ product.description|slice:":90" }}
                                    {% if product.description|length > 90 %}...{% endif %}
                                </p>

                            </div>
                            <!-- Card content -->

                        </div>
                        <!-- Card -->

                    </section>
                    <!-- Section: Live preview -->
                </div>
            {% endfor %}


        </div>

    </section>
    <!-- Section: Cascading cards -->

</div>

templates/user_login.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Ebay Auction</title>

    <!-- Font Icon -->
    <link rel="stylesheet" href="{% static 'register/fonts/material-icon/css/material-design-iconic-font.min.css' %}">

    <!-- Main css -->
    <link rel="stylesheet" href="{% static 'register/css/style.css' %}">
    <link rel="stylesheet" href="{% static 'style.css' %}">

    
</head>
<body>

    <!-- Sing in  Form -->
<section class="sign-in">
    <div class="container">
        <div class="signin-content">
            <div class="signin-image" id="m">
                <figure><img src="{% static 'register/images/signin-image.jpg' %}" alt="sing up image"></figure>
                <a href="{% url 'authentication:admin-login' %}" class="signup-image-link" id="s">Admin Login</a>
            </div>

            <div class="signin-form">
                <h2 class="form-title">Sign in</h2>
                <form action="{% url 'authentication:user-login' %}" method="POST" class="register-form" id="login-form">
                    {% csrf_token %}
                    <div class="form-group">
                        <label for="username"><i class="zmdi zmdi-account material-icons-name"></i></label>
                        <input type="email" name="email" id="email" placeholder="email" required/>
                    </div>


                    <div class="form-group form-button">
                        <input type="submit" name="user-login" id="login" class="form-submit" value="Log in"/>
                    </div>
                    
                </form>
                
            </div>
        </div>
    </div>
</section>


    <!-- JS -->
    <script src="{% static 'register/vendor/jquery/jquery.min.js' %}"></script>
    <script src="{% static 'register/js/main.js' %}"></script>
</body><!-- This templates was made by Colorlib (https://colorlib.com) -->
</html>